# Generated by Django 5.1.4 on 2025-01-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_name', models.CharField(max_length=100)),
                ('full_address', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('panchayath', models.CharField(max_length=100)),
                ('thaluk', models.CharField(max_length=100)),
                ('contact', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Camp_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=100)),
            ],
        ),
    ]
