# Generated by Django 5.1.4 on 2025-01-09 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_login_delete_camp_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='login_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.login'),
        ),
        migrations.AlterField(
            model_name='camp',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
