# Generated by Django 5.1.4 on 2025-01-16 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='camp')),
                ('full_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=100)),
                ('aadhar_no', models.CharField(max_length=100)),
                ('panchayath', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('thaluk', models.CharField(max_length=100)),
                ('current_date', models.DateField(auto_now_add=True)),
                ('camp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.login')),
            ],
        ),
    ]
