# Generated by Django 5.1.4 on 2025-01-26 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_campuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampNeeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs', models.TextField(max_length=100)),
                ('current_date', models.DateField(auto_now_add=True)),
                ('login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.login')),
            ],
        ),
    ]
