# Generated by Django 5.1.4 on 2025-01-26 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_campneeds_login_id_campneeds_camp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campneeds',
            name='camp_id',
        ),
    ]
