# Generated by Django 5.1.4 on 2025-01-26 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_campneeds_camp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campneeds',
            name='camp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.camp'),
        ),
    ]
