# Generated by Django 5.1.4 on 2025-01-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_campneeds_camp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campneeds',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
