# Generated by Django 5.1.4 on 2025-01-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_volunteer_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='date_of_birth',
            field=models.CharField(max_length=30),
        ),
    ]
