# Generated by Django 5.1.4 on 2025-02-01 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_volunteer_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_message', models.TextField(max_length=50)),
                ('current_date', models.DateField()),
                ('login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.camp')),
            ],
        ),
    ]
