# Generated by Django 5.1.4 on 2025-02-02 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_campalert_current_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_volunteers', models.CharField(max_length=100)),
                ('volunteer_details', models.TextField(max_length=100)),
                ('current_date', models.DateField(auto_now_add=True)),
                ('login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.camp')),
            ],
        ),
    ]
