# Generated by Django 5.1.4 on 2025-02-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_volunteerrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campalert',
            name='current_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
