# Generated by Django 5.1.4 on 2025-02-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_campalert_current_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campalert',
            name='current_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
