# Generated by Django 5.1.4 on 2025-02-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_allocate'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='allocation',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
