# Generated by Django 5.1.4 on 2025-02-07 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_volunteer_allocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='allocation',
        ),
    ]
