# Generated by Django 5.1.4 on 2025-02-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_volunteer_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='allocation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
