# Generated by Django 5.1.4 on 2025-02-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_volunteerrequest_totalallocated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerrequest',
            name='no_of_volunteers',
            field=models.IntegerField(default=0),
        ),
    ]
