# Generated by Django 5.1.4 on 2025-02-12 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_volunteerrequest_no_of_volunteers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_sub', models.TextField(max_length=100)),
                ('complaint', models.TextField(max_length=500)),
                ('current_date', models.DateField(auto_now_add=True)),
                ('login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.login')),
            ],
        ),
    ]
