# Generated by Django 5.1.4 on 2025-02-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_volunteerrequest_no_of_volunteers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='allocation',
            field=models.CharField(default='false', max_length=100),
        ),
    ]
