# Generated by Django 5.1.4 on 2025-02-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_volunteer_allocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='allocation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
