# Generated by Django 5.1.4 on 2025-02-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_sub',
            field=models.CharField(max_length=100),
        ),
    ]
