# Generated by Django 5.1.4 on 2025-02-12 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_complaint_complaint_sub'),
        ('app', '0030_alter_volunteer_allocation'),
    ]

    operations = [
    ]
