# Generated by Django 5.1.4 on 2025-02-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_merge_20250212_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='reply',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
