<<<<<<< HEAD
# Generated by Django 5.1.4 on 2025-02-13 06:38
=======
# Generated by Django 5.1.4 on 2025-02-12 10:45
>>>>>>> c69c3fddae64a0b84aad6abe9f7609314fd7d778

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_complaint_reply'),
        ('app', '0032_duty'),
    ]

    operations = [
    ]
