# Generated by Django 5.1.4 on 2025-02-12 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_merge_0032_complaint_reply_0032_duty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duty',
            old_name='camp',
            new_name='camp_id',
        ),
        migrations.RenameField(
            model_name='duty',
            old_name='volunteer',
            new_name='volunteer_id',
        ),
    ]
