# Generated by Django 5.1.4 on 2025-02-13 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_merge_0032_complaint_reply_0032_duty'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundAllocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fund')),
                ('full_name', models.CharField(max_length=100)),
                ('full_address', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('panchayath', models.CharField(max_length=100)),
                ('ration_card_no', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('other_details', models.TextField(max_length=100)),
                ('current_date', models.DateField(auto_now_add=True)),
                ('login_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.login')),
            ],
        ),
    ]
