# Generated by Django 5.1.4 on 2025-02-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_rename_camp_duty_camp_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duty',
            name='duty',
            field=models.TextField(default='Not Scheduled Yet'),
        ),
    ]
