# Generated by Django 5.1.4 on 2025-02-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_duty_duty'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='duty_status',
            field=models.CharField(default='Not Scheduled', max_length=100),
        ),
        migrations.AlterField(
            model_name='duty',
            name='duty',
            field=models.TextField(),
        ),
    ]
