# Generated by Django 5.1.4 on 2025-02-12 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_remove_volunteer_duty_status_allocate_duty_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocate',
            name='duty_status',
        ),
    ]
