# Generated by Django 5.1.4 on 2025-02-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_allocate_duty_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocate',
            name='duty_status',
            field=models.CharField(default='Not Scheduled', max_length=100),
        ),
    ]
