# Generated by Django 5.1.4 on 2025-02-12 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_allocate_duty_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocate',
            name='duty_status',
        ),
    ]
