# Generated by Django 5.1.4 on 2025-02-13 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_fundallocationmodel'),
        ('app', '0041_allocate_duty_status'),
    ]

    operations = [
    ]
