# Generated by Django 5.1.4 on 2025-02-13 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_merge_20250213_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundallocationmodel',
            name='camp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.camp'),
        ),
        migrations.AddField(
            model_name='fundallocationmodel',
            name='volunteer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.volunteer'),
        ),
    ]
