# Generated by Django 5.1.4 on 2025-02-14 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_fundallocationmodel_camp_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_on_card', models.CharField(max_length=100)),
                ('card_no', models.IntegerField()),
                ('expiring_date', models.CharField(max_length=10)),
                ('cvv_no', models.IntegerField()),
                ('amount', models.CharField(max_length=50)),
                ('current_date', models.DateField(auto_now_add=True)),
                ('req_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.fundallocationmodel')),
            ],
        ),
    ]
