# Generated by Django 5.1.4 on 2025-02-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_fundpayment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundpayment',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fundpayment',
            name='card_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fundpayment',
            name='cvv_no',
            field=models.IntegerField(default=0),
        ),
    ]
