# Generated by Django 5.1.4 on 2025-02-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_alter_fundpayment_amount_alter_fundpayment_card_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundallocationmodel',
            name='camp_id',
        ),
        migrations.RemoveField(
            model_name='fundallocationmodel',
            name='volunteer_id',
        ),
        migrations.AddField(
            model_name='fundallocationmodel',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
