# Generated by Django 5.1.4 on 2025-02-14 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_remove_fundallocationmodel_camp_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundallocationmodel',
            name='camp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.camp'),
        ),
        migrations.AddField(
            model_name='fundallocationmodel',
            name='volunteer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.volunteer'),
        ),
        migrations.CreateModel(
            name='MissingPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='person')),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('other_details', models.TextField()),
                ('public_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.public')),
            ],
        ),
    ]
