# Generated by Django 5.1.4 on 2025-02-20 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_fundallocationmodel_camp_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='station_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.police'),
        ),
    ]
