# Generated by Django 5.1.4 on 2025-02-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_remove_missingperson_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='case_status',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
