# Generated by Django 5.1.4 on 2025-02-27 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_missingperson_case_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingperson',
            name='case_status',
        ),
    ]
