# Generated by Django 5.1.4 on 2025-02-27 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_remove_missingperson_case_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MissingPerson',
        ),
    ]
