# Generated by Django 5.1.4 on 2025-02-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_alter_missingperson_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingperson',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
