# Generated by Django 5.1.4 on 2025-02-28 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_emergencyalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enq', models.TextField()),
                ('current_date', models.DateField(auto_now_add=True)),
                ('response', models.CharField(blank=True, max_length=50, null=True)),
                ('camp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.login')),
                ('public', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.public')),
            ],
        ),
    ]
