# Generated by Django 5.1.4 on 2025-02-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
