# Generated by Django 5.1.4 on 2025-02-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_alter_enquiry_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='response',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
