# Generated by Django 5.1.4 on 2025-03-01 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_alter_enquiry_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=30)),
                ('vehicle_num', models.CharField(max_length=15)),
                ('missing_place', models.CharField(max_length=20)),
                ('missing_date', models.CharField(max_length=10)),
                ('current_date', models.DateField(auto_now_add=True)),
                ('police', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.police')),
                ('public', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.login')),
            ],
        ),
    ]
