# Generated by Django 5.1.4 on 2025-03-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
