# Generated by Django 5.1.4 on 2025-03-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_vehicle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='duty',
            name='spec',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
