# Generated by Django 5.1.4 on 2025-03-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_duty_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duty',
            name='spec',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
